services:
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      # Mount the config file
      - ./config/application-poc.yaml:/app/config/application.yaml
      # Mount a volume for the SQLite metadata DB
      - orchestrator-data:/app/db
      # Mount the externalized schema output directory
      - ./generated-schema:/app/generated-schema
    depends_on:
      - source-db
      - target-db
      - target-db-pg
      - shardingsphere-proxy
    environment:
      # Tell Spring Boot where to find the external config
      - SPRING_CONFIG_LOCATION=file:/app/config/application.yaml
      # Set the working dir for SQLite
      - SQLITE_DB_PATH=/app/db/orchestrator.db

  source-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=source_password
      - MYSQL_DATABASE=sourcedb
    volumes:
      - ./scripts/init-source.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --binlog-row-image=FULL --gtid-mode=ON --enforce-gtid-consistency=ON --log-slave-updates=ON --server-id=1

  target-db:
    image: mysql:8.0
    ports:
      - "3307:3306" # Map to a different host port
    environment:
      - MYSQL_ROOT_PASSWORD=target_password
      - MYSQL_DATABASE=targetdb
    command: --default-authentication-plugin=mysql_native_password --server-id=2

  target-db-pg:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=target_password_pg
      - POSTGRES_DB=targetdb_pg
    command: postgres -c 'wal_level=logical' # Required for CDC

  zookeeper:
    image: zookeeper:3.9
    ports:
      - "2181:2181"

  shardingsphere-proxy:
    image: apache/shardingsphere-proxy:5.5.2
    ports:
      - "3309:3307" # Main proxy port (if we were proxying)
    volumes:
      - ./ext-lib:/opt/shardingsphere-proxy/ext-lib
      - ./config/shardingsphere-server-template.yaml:/opt/shardingsphere-proxy/conf/global.yaml
    depends_on:
      - zookeeper

volumes:
  orchestrator-data: